" To update the status line, so that you have the colourful status bar. If it is not set you will not see any change when you start up vim.
" Set a status line
set laststatus=2
 
" Set encoding so that your fonts look okay.
set encoding=utf-8
 
execute pathogen#infect()
filetype plugin indent on
 
" Enable powerline fonts
let g:airline_powerline_fonts = 1

"let g:airline_theme='tomorrow'
let g:airline_theme='powerlineish'

" Return to last edit position when opening files (You want this!)
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
